import json

import requests
import os
country_list = ["GD", "DM", "LK", "MN", "PE", "XK", "MO", "AM", "TW", "LY", "SA", "NG", "GQ", "BR", "ID", "SY", "DO",
                "PG", "FR", "CZ", "BY", "DK", "KR", "CI", "LB", "BZ", "CW", "CO", "ET", "AD", "QA", "UZ", "TR", "PR",
                "HT", "ZW",
                "BB", "SE", "AT", "AO", "AE", "ME", "IR", "NI", "DE", "UY", "JO", "SI", "BF", "CD", "YE", "ZA", "GT",
                "SZ", "BM",
                "PW", "HN", "MQ", "NE", "IN", "JM", "MR", "VE", "GR", "AL", "IE", "SN", "PS", "TT", "CR", "TZ", "RW",
                "RE", "EG",
                "MA", "HK", "VI", "CA", "NL", "CY", "SK", "CH", "CN", "KZ", "CM", "AZ", "TC", "HU", "NP", "TH", "BS",
                "RO", "BG",
                "RS", "EC", "BN", "SO", "YT", "US", "JP", "AF", "LA", "VC", "GH", "BH", "GY", "AR", "GA", "NA", "GU",
                "KH", "MX",
                "BD", "PK", "GE", "KY", "GL", "MM", "VU", "FI", "PH", "BQ", "ER", "MP", "RU", "CU", "TN", "LT", "BE",
                "EE", "MW",
                "LU", "DZ", "VN", "LV", "MD", "MU", "SB", "SV", "HR", "IL", "NC", "KW", "FM", "MY", "GF", "PY", "MG",
                "KE", "LC",
                "TG", "PA", "BW", "CL", "SC", "KG", "VG", "PF", "ES", "UA", "GN", "CG", "ML", "GM", "IT", "SG", "PT",
                "BO", "FJ",
                "NZ", "NO", "SR", "GB", "PL", "MK", "BA", "GP", "CV", "MT", "IQ", "AU"
                ]
proxy_rack_country_cities_list = {"GD": ["Saint George's"], "DM": ["Roseau"], "LK": ["Colombo", "Dehiwala", "Galle", "Panadura", "Wattala"],
            "MN": ["Ulan Bator", "Nuga"], "PE": ["Trujillo", "Pucallpa", "Arequipa", "Viru", "Lima", "Cusco"],
            "XK": ["Pristina"], "MO": ["Macao"], "AM": ["Yerevan"],
            "TW": ["Chiayi County", "Hsinchu", "Yilan", "Kaohsiung City", "Taipei", "Yunlin", "Zhongli District",
                   "Chang-hua", "Chiayi City", "Neipu", "Zhubei", "Jian", "Taoyuan District", "Taichung", "New Taipei",
                   "Hualien City", "Xitun", "Bade District", "Luzhu", "Tainan City", "Pingtung City", "Hsinchu County"],
            "LY": ["Ajdabiya", "At Taj", "Tripoli", "Benghazi", "Zliten", "Misratah", "Awjilah", "Ghat", "Al Marj"],
            "SA": ["Makkah", "Jeddah", "Riyadh", "Dammam", "Medina", "Eastern Province"],
            "NG": ["Lagos", "Ilorin", "Benin City"], "GQ": ["Bicurga", "Malabo"],
            "BR": ["Sao Jose do Vale do Rio Preto", "Franca", "Chapadao Do Sul", "Araioses", "Teresina",
                   "Belo Horizonte", "Curitiba", "Maceió", "Itapetininga", "Balneário Camboriú", "Rio Maria",
                   "Ipatinga", "Santo André", "Pouso Alegre", "Praia Grande", "Brasília", "Fortaleza",
                   "Jaboatao dos Guararapes", "Guaratuba", "Várzea Grande", "Dom Cavati", "Araguaína", "Aracaju",
                   "Osasco", "Rio de Janeiro", "Novo Hamburgo", "Sangao", "Santos", "Viamão", "Saudades", "Betim",
                   "Paracatu", "Garca", "Sao Jose do Rio Preto", "Sorocaba", "Paulista", "Vinhedo", "Uberaba",
                   "Limeira", "Maringá", "Teotonio Vilela", "Vila Velha", "Manhuacu", "Jaraguá do Sul", "Vitória",
                   "Ariquemes", "Nova Iguaçu", "Sao Jose de Piranhas", "João Pessoa", "Vitória da Conquista",
                   "Virgem da Lapa", "Assis", "Serra", "Farroupilha", "Fazenda Rio Grande", "Guarulhos",
                   "Santa Cruz do Sul", "Ijui", "Imperatriz", "Lencois", "Malta", "Cafelandia", "Porto Alegre",
                   "Caxias do Sul", "Pintadas", "Campinas", "Jacunda", "São Paulo", "Irece", "Anápolis", "Lagarto",
                   "Dois Irmaos", "Manaus", "Porto Velho", "Parobe", "Ourinhos", "Sumaré", "Boa Vista",
                   "Ribeirão Preto", "Goiânia", "São Caetano do Sul"],
            "ID": ["Gresik", "Bengkulu", "Keputih", "Banjarmasin", "Magelang", "Kupang", "Balikpapan", "Palembang",
                   "Pandeglang", "Karawang", "Bandar Lampung", "Cilegon", "Kalideres", "Subang", "Yogyakarta", "Demak",
                   "Ambon City", "Temanggung", "Sragen", "Blora", "Brebes", "Karanganyar Wetankali", "Semarang",
                   "Bekasi", "Jepara", "Cilacap", "Bintaro", "Manado", "Bukittinggi", "Pemalang", "Pangkalpinang",
                   "Mojosongo", "Magetan", "Manggadua Selatan", "Buaran", "Jakarta", "Pontianak", "Tangerang",
                   "Sumedang", "Pekanbaru", "Blitar", "Sleman", "Menteng", "Cibeber", "Rembangan", "Pati", "Sukabumi",
                   "Prapattunggal", "Ciamis", "Kendari", "Ponorogo", "Natar", "Tanjung Pinang", "Mojokerto",
                   "Pangandaran", "Lamongan", "Nabire", "Gorontalo", "Boyolali", "Sumbawa Besar", "Babakangarut",
                   "Palu", "Wonogiri", "Tegal", "Palangkaraya", "Bogor", "Makassar", "South Tangerang", "Madiun",
                   "Tuban", "Malang", "Perwira", "Jambi City", "Klaten", "Bulanbulan", "Purwokerto", "Merauke",
                   "Cipulir", "Sidoarjo", "Bontang", "Bukit Duri", "Depok", "Tenggarong", "Jatimakmur", "Bedalipermai",
                   "Tanjung Balai", "Mataram", "Serang", "Purbalingga", "Manokwari", "Papua", "Tasikmalaya", "Denpasar",
                   "Ngawi", "Banyumas", "Samarinda", "Surabaya", "Sukoharjo", "Trenggalek", "Probolinggo",
                   "Kebon Kelapa", "Ternate", "Kebumen Satu", "Indramayu", "Batam", "Padang", "Jember", "Selong",
                   "Surakarta", "Lhokseumawe", "Pasuruan", "Pekalongan", "Sorong", "Bima", "Srengseng", "Lumajang",
                   "Cirebon", "Kediri", "Banyuwangi", "Tarakan", "Medan", "Ancol Timur", "Jayapura", "Baru Ilir",
                   "Banda Aceh", "Bandung", "Pondok Pinang", "Jati"],
            "DO": ["Santo Domingo Este", "Nagua", "San Francisco de Macorís", "La Boca de Mao Abajo", "Cabarete",
                   "Santa Cruz de Barahona", "San Isidro", "Santo Domingo", "Cotui", "Las Terrenas", "San Cristobal",
                   "Santiago de los Caballeros", "San Pedro de Macorís", "Sabaneta de Yasica", "Concepción de la Vega",
                   "Dajabon", "Los Alcarrizos", "Puerto Plata", "Bonao", "Sosua, Cabarete", "Licey al Medio",
                   "Washington", "Provincia de Barahona", "La Romana", "Santo Domingo Oeste", "Guananico",
                   "Hato Mayor del Rey", "Gaspar Hernandez"], "PG": ["Lae"],
            "FR": ["Draveil", "Issy-les-Moulineaux", "Montevrain", "Strasbourg", "Rouen", "Montreuil-Juigne", "Metz",
                   "Chatillon-sur-Loire", "Vire", "Eclance", "Marseille", "Cannes", "Dun-sur-Auron", "Bandol", "Saumur",
                   "Sezanne", "Les Essarts-le-Roi", "Lyon", "Les Sables-d'Olonne", "Thonon-les-Bains", "Bordeaux",
                   "Angais", "Vélizy-Villacoublay", "Sète", "Molsheim", "Choisy-le-Roi", "Bully-les-Mines",
                   "Boulogne-Billancourt", "Roubaix", "Saint-Etienne", "Perpignan", "Sélestat",
                   "Sainte-Geneviève-des-Bois", "Aubervilliers", "Cornas", "Noisy-le-Grand", "Paris",
                   "Saint-Cheron-des-Champs", "Bouxieres-sous-Froidmont"],
            "CZ": ["Bilina", "Liberec", "Přerov", "Zbraslavice", "Kutná Hora", "Frýdek-Místek", "Zlín", "Prague",
                   "Tábor", "Most", "Velke Brezno", "Sternberk"],
            "BY": ["Pinsk", "Gomel", "Vitebsk", "Mogilev", "Minsk", "Brest"],
            "DK": ["Esbjerg", "Aarhus", "Odense", "Frederiksberg"],
            "KR": ["Anseong", "Jecheon", "Uiwang", "Bucheon-si", "Mokpo", "Suyeong-gu", "Seodaemun-gu",
                   "Yeongdeungpo-gu", "Namhae-gun", "Yangp'yong", "Jungnang-gu", "Daegu", "Seongdong-gu", "Busanjin-gu",
                   "Geumjeong-gu", "Gunsan", "Uiseong-gun", "Kwangyang", "Bupyeong-gu", "Gyeongsan-si", "Yongheung",
                   "Ulju-gun", "Dongjak-gu", "Muju-gun", "Pocheon-si", "Yeongcheon-si", "Yangyang-gun", "Tangjin",
                   "Yangcheon-gu", "Hongseong-gun", "Gangdong-gu", "Taean-gun", "Dalseong-gun", "Gangneung",
                   "Gwangmyeong", "Seongju-gun", "Nonsan", "Songpa-gu", "Suseong-gu", "Chinch'on", "Changnyeong",
                   "Iksan", "Suncheon", "Sejong", "Gyeonggi-do", "Namyangju", "Yongsan-gu", "Yongin-si",
                   "Dongdaemun-gu", "Seocho-gu", "Ansan-si", "Dalseo-gu", "Pohang", "Nowon-gu", "Yeonsu-gu", "Gwacheon",
                   "Miryang", "Namdong-gu", "Anyang-si", "Osan", "Hanam", "Haeundae-gu", "Busan", "Pyeongtaek-si",
                   "Siheung-si", "Gwangjin-gu", "Goseong-gun", "Sasang-gu", "Paju", "Mapo-gu", "Yuseong-gu",
                   "Icheon-si", "Suwon", "Cheonan", "Yeonje-gu", "Hongch'on", "Gapyeong County", "Seogwipo",
                   "Jongno-gu", "Yeongwol-gun", "Gimpo-si", "Areannamkwaengi", "Guro-gu", "Uijeongbu-si", "Cheongju-si",
                   "Chungju", "Goyang-si", "Saha-gu", "Gangbuk-gu", "Daedeok-gu", "Ulsan", "Nam-gu", "Seongnam-si",
                   "Chuncheon", "Gangseo-gu", "Seongbuk-gu", "Jeollabuk-do", "Eunpyeong-gu", "Jung-gu", "Seoul",
                   "Gwangju", "Gwangmyeong-si", "Geoje", "Yeongdong-gun", "Yecheon", "Wanju", "Chilgok-gun", "Boryeong",
                   "Gangnam-gu", "Gyeongju", "Goheung-gun", "Asan", "Donggu", "Buan-gun", "Hwaseong-si", "Taejeon",
                   "Paju-si", "Dong-gu", "Dobong-gu", "Gyeyang-gu", "Andong", "Muan", "Jeonju", "Geumcheon-gu",
                   "Gwangsan-gu", "Incheon", "Yangju", "Gimcheon", "Naju", "Seo-gu", "Gwanak-gu", "Tongyeong", "Jinju",
                   "Pyeongchang", "Jeongseon-gun", "Pohang-si", "Dongducheon-si", "Wonju", "Jeju City", "Yeosu",
                   "Yangsan", "Buk-gu", "Gimhae", "Gumi", "Gimje-si", "Seosan City", "Changwon", "Ganghwa-gun",
                   "Gijang-gun", "Guri-si", "Yeoncheon-gun"], "CI": ["Abidjan"], "LB": ["Beirut", "Fanar"],
            "BZ": ["Belize City", "Orange Walk", "San Ignacio"], "CW": ["Willemstad"],
            "CO": ["Garzón", "Bucaramanga", "Envigado", "San Pelayo", "Arauca", "Supata", "Saravena", "Caucasia",
                   "Bogotá", "San Gil", "Santiago de Cali", "Tuluá", "Barranquilla", "San José del Guaviare",
                   "San Rafael", "Pereira", "Pasto", "Risaralda", "Jamundi", "Guadalajara de Buga", "Valledupar",
                   "Cúcuta", "Ibague", "Agustin Codazzi", "Andalucia", "Aguachica", "San Andres de Palomo", "Cartagena",
                   "Medellín", "Acacias", "Chia", "San Onofre", "Ipiales"],
            "ET": ["Nazret", "Gambela", "Harar", "Jijiga", "Addis Ababa", "Kuta Ber", "Dire Dawa"],
            "AD": ["Andorra la Vella"], "QA": ["Doha"], "UZ": ["Gurlan", "Tashkent", "Bukhara"],
            "TR": ["Sanliurfa", "Bayrampasa", "Bagcilar", "Edirne", "Izmir", "Denizli", "Zonguldak", "Antalya",
                   "Diyarbakır", "Kosekoy", "Istanbul", "Bursa", "Ankara", "Adıyaman", "Antakya", "Adana"],
            "PR": ["Bayamón", "Manati", "Ciales", "San German", "San Juan"], "HT": ["Port-au-Prince"], "ZW": ["Harare"],
            "BB": ["Christ Church", "Bridgetown"],
            "SE": ["Spanga", "Sollentuna", "Ludvika", "Hultsfred", "Stockholm", "Sundsvall", "Bollnaes", "Karlstad"],
            "AT": ["Graz", "Hoechst", "Bregenz", "Kirchbichl", "Goestling an der Ybbs", "Ried im Innkreis", "Hard",
                   "Sankt Johann in Tirol", "Innsbruck", "Dornbirn", "Vienna", "Kematen an der Ybbs", "Going",
                   "Lustenau"], "AO": ["Luanda", "Lubango"], "AE": ["Dubai", "Abu Dhabi"], "ME": ["Rozaje", "Budva"],
            "IR": ["Tehran"], "NI": ["Managua"],
            "DE": ["Gelsenkirchen", "Elsterwerda", "Siegen", "Frankfurt am Main", "Trier", "Freudenstadt",
                   "Bietigheim-Bissingen", "Dresden", "Cologne", "Bad Durrheim", "Hilden", "Bremen", "Namborn", "Kaaks",
                   "Beckingen", "Cochem", "Kassel", "Kleve", "Lüneburg", "Borken", "Monheim am Rhein", "Landau",
                   "Bingen am Rhein", "Leipzig", "Nuremberg", "Senftenberg", "Monschau", "Bad Salzungen", "Buechel",
                   "Düsseldorf", "Hamburg", "Buedingen", "Essen", "Laichingen", "Fuerstenwalde", "Ibbenbueren",
                   "Oberursel", "Pfaffenhofen an der Ilm", "Duisburg", "Ingolstadt", "Schwalbach", "Erfurt", "Soltau",
                   "Zwickau", "Halberstadt", "Bad Pyrmont", "Osnabrück", "Fuldabruck", "Bad Bevensen", "Plattling",
                   "Haltern am See", "Gottmadingen", "Ludwigshafen am Rhein", "Bendorf", "Brandenburg",
                   "Bad Neuenahr-Ahrweiler", "Reutlingen", "Poessneck", "Oberhaching", "Uelzen", "Coburg", "Koblenz",
                   "Bad Kreuznach", "Friedrichsdorf", "Olching", "Bardowick", "Kronberg", "Reinbek", "Bayreuth",
                   "Gotha", "Mainz", "Bienenbuttel", "Schweinfurt", "Heilbronn", "Braunschweig", "Chemnitz", "Munich",
                   "Buxtehude", "Ruppertsecken", "Bielefeld", "Alzenau in Unterfranken", "Inchenhofen", "Bretten",
                   "Meiningen", "Bochum", "Augsburg", "Muehldorf", "Bonn", "Wiesbaden", "Bad Friedrichshall",
                   "Rielasingen-Worblingen", "Loecknitz", "Nagold", "Rennertshofen", "Limburg an der Lahn",
                   "Oberhausen", "Ettlingen", "Jena", "Bad Freienwalde", "Untergriesbach", "Magdeburg", "Asslar",
                   "Karlsruhe", "Rostock", "Aschersleben", "Osterholz-Scharmbeck", "Rehlingen-Siersburg", "Mannheim",
                   "Berlin", "Neu-Isenburg", "Kaiserslautern", "Gaildorf", "Neusass", "Gangkofen", "Gunzenhausen",
                   "Leverkusen", "Remagen", "Krefeld", "Hanover"], "UY": ["Montevideo", "Aguada"],
            "JO": ["Irbid", "Amman", "Zarqa", "Salt", "Balqa"],
            "SI": ["Kamnik", "Trbovlje", "Semic", "Divača", "Maribor", "Domžale", "Ljubljana"], "BF": ["Ouagadougou"],
            "CD": ["Inongo"], "YE": ["Sanaa"],
            "ZA": ["Letaba", "Secunda", "Tzaneen", "Westonaria", "Ladybrand", "Stellenbosch", "Benoni", "Mafikeng",
                   "Brits", "Grahamstown", "Polokwane", "Moorreesburg", "Sedgefield", "Hartswater", "Lephalale",
                   "Cape Town", "Krugersdorp", "Springs", "Vanderbijlpark", "Rustenburg", "Thohoyandou", "East London",
                   "Villiersdorp", "Paarl", "St Francis Bay", "Pretoria", "Bloemfontein", "Durban", "Worcester",
                   "Kuruman", "Robertson", "Nelspruit", "Kranskop", "Rabie Ridge", "Centurion", "Johannesburg",
                   "Potchefstroom", "Vredenburg", "Richards Bay", "Somerset West", "Kempton Park", "Cradock",
                   "Port Elizabeth", "Pietermaritzburg", "Despatch", "Theunissen", "Atlantis", "Queenstown"],
            "GT": ["San Marcos", "Peten", "Quetzaltenango", "Villa Nueva", "Puerto Barrios", "Guatemala City",
                   "Esquipulas", "Zacapa"], "SZ": ["Mbabane"], "BM": ["Hamilton", "Devonshire Parish"], "PW": ["Koror"],
            "HN": ["Tegucigalpa", "San Pedro Sula"], "MQ": ["Fort-de-France"],
            "IN": ["Ahmedabad", "Guntur", "Ghaziabad", "Vyara", "Bhubaneswar", "Varanasi", "Cherthala", "Kanpur",
                   "Sikar", "Palakollu", "Sonipat", "Delhi", "Patna", "Kozhikode", "Deoria", "Bikaner", "Coimbatore",
                   "Hubli", "Gurgaon", "Shillong", "Churu", "Kumily", "Dombivali", "Aurangabad", "Mohali", "Bharuch",
                   "Ambala", "Visakhapatnam", "Warangal", "Alangad", "Mamit", "Morena", "Jamnagar", "Gondal",
                   "Jalandhar", "Ongole", "Karaikal", "Dindigul", "Imphal", "Valsad", "Puducherry", "Mayapur", "Mumbai",
                   "Thoothukudi", "Pune", "Bhopal", "Khammam", "Bahadurgarh", "Shimla", "Pilani", "Medinipur",
                   "Navi Mumbai", "Kakinada", "Sambalpur", "Namakkal", "Bijnor", "Bengaluru", "Ramanathapuram",
                   "Khandwa", "Vadodara", "Agra", "Baraut", "Jalalpore", "New Delhi", "Vaddangi", "Hyderabad",
                   "Gonda City", "Bilimora", "Beed", "Asansol", "Nashik", "Amritsar", "Gondia", "Guwahati", "Madurai",
                   "Thanjavur", "Chennai", "Jhajjar", "Anantapur", "Kumbakonam", "Kota", "Bareilly", "Panipat", "Jalna",
                   "Vijayawada", "Dehradun", "Kochi", "Salem", "Vellore", "Jhansi", "Surat", "Thane", "Lucknow",
                   "Kurnool", "Faridabad", "Ateli Mandi", "Nagpur", "Indore", "Ajmer", "Jamshedpur", "Krishnagiri",
                   "Panvel", "Karur", "Jorhat", "Kolkata", "Malappuram", "Balasore", "Hisar", "Palladam", "Morvi",
                   "Noida", "Thrissur", "Howrah", "Brahmapur", "Jaipur", "Ludhiana", "Ankleshwar", "Raipur", "Nellore",
                   "Kollam", "Aizawl", "Virar", "Sitarganj", "Mitauli", "Dhanbad", "Erode", "Patan", "Raurkela",
                   "Trivandrum", "Alappuzha", "Pathankot", "Kasaragod", "Mira Road", "Tiruchi", "Chandigarh", "Aligarh",
                   "Rajkot", "Baddi", "Erumanur", "Greater Noida", "Churachandpur", "Meerut", "Kannur", "Deesa",
                   "Udaipur"], "JM": ["May Pen", "Kingston", "Parish of Saint Ann"], "MR": ["Nouakchott"],
            "VE": ["Maracay", "Coro", "Yaritagua", "Ciudad Ojeda", "Miranda", "Biruaca", "Maiquetia", "Los Teques",
                   "Maturín", "Anaco", "San Antonio de Los Altos", "San Bernardino", "Punto Fijo", "Cabimas",
                   "Catia La Mar", "La Victoria", "Guatire", "Cua", "Duaca", "Sucre", "Maracaibo", "Los Dos Caminos",
                   "Puerto Cabello", "Valera", "San Felipe", "Araure", "El Tigre", "Mariara", "Porlamar",
                   "Ciudad Guayana", "La Asunción", "Barinas", "Catia", "Nueva Esparta", "Valencia", "Calabozo",
                   "Trujillo", "Mérida", "Guanare", "Turmero", "Puerto Ordaz and San Felix", "Cagua", "Vargas", "Zulia",
                   "San Carlos", "Ciudad Bolívar", "Caricuao", "Alto Barinas", "Abejales", "San Cristóbal",
                   "Distrito Federal", "Barcelona", "Libertador", "El Pilar", "Cocote", "Carrizal", "Aragua", "Caracas",
                   "La Guaira", "Ocumare", "Carúpano", "Cumaná", "Acarigua", "San Fernando de Apure", "Vigia",
                   "San Juan de los Morros", "Nirgua", "Barquisimeto", "Puerto Cruz", "Lecherias", "Cabudare",
                   "El Guarenal", "Tocuyito", "Guacara"],
            "GR": ["Athens", "Glyfada", "Marousi", "Thessaloniki", "Piraeus", "Nea Liosia", "Volos", "Thebes",
                   "Rhodes"], "AL": ["Vlorë", "Lushnje", "Tirana", "Fier"], "IE": ["Dublin"], "SN": ["Thiès", "Dakar"],
            "PS": ["Salfit", "Hebron", "Bethlehem", "Palestine", "Nablus", "Tulkarm", "Gaza", "Khan Yunis", "Ramallah",
                   "Jenin"],
            "TT": ["Williamsville", "Port of Spain", "Trincity", "Arima", "Fyzabad", "Gasparillo", "Preysal",
                   "San Fernando", "Chaguanas", "Scarborough", "Saint Augustine"], "CR": ["Alajuela", "San José"],
            "TZ": ["Arusha", "Dodoma"], "RW": ["Kigali"],
            "RE": ["Sainte-Anne", "L'Etang-Sale", "Saint-Benoit", "Petite Ile"],
            "EG": ["Beheira", "6th of October City", "Al Amiriyah", "Al Hawamidiyah", "Mit Ghamr", "Bilqas", "Banha",
                   "Agouza", "Kafr ash Shaykh", "Kafr ash Shaykh Hilal", "Arish", "Asyut", "Sohag", "Qina", "Hurghada",
                   "Rosetta", "Al Ma`adi", "Al Qusiyah", "Baltim", "Al `Atabah", "Al 'Ashir min Ramadan", "Biyala",
                   "Qalyubia", "Madinat an Nasr", "Faraskur", "Dokki", "Zefta", "Bani Mazar", "Awsim", "Tahta",
                   "Sidi Bishr", "Heliopolis", "Esna", "Madinat as Sadat", "Helwan", "Al Haram", "Qus",
                   "Al Mahallah al Kubra", "Juhaynah", "Kafr ad Dawwar", "Aswan", "Matay", "Cairo Governorate", "Giza",
                   "Al Mansurah", "Talkha", "Shubra", "Hihya", "Port Said", "Al Qahirah al Jadidah", "Damanhur",
                   "Minya", "Az Zamalik", "Dikirnis", "Miami", "Al Fayyum", "Al Fashn", "Shibîn el-Qanâṭir", "Gharbia",
                   "El Alamein", "Mit Birah wa Kafr ash Shahid", "Sharqia", "Zagazig", "Bi'r al `Abd", "Aga",
                   "Damietta", "Luxor", "Suez", "Ibshaway", "Cairo", "Ismailia", "Alexandria", "Munuf", "Samannud",
                   "Hawsh `Isa", "Tanta", "Tima", "Al Marj", "Kafr Shukr", "Tala", "Badr", "Bani Suwayf", "Dakahlia",
                   "Bilbeis", "Bulaq Abu al `Ila"],
            "MA": ["Salé", "Bejaad", "Berkane", "Imintanout", "Fes", "El Jadida", "Kenitra", "Taounate", "Azrou",
                   "Laayoune", "Douar Laayoune", "Sidi Ifni", "Bouskoura", "Berrechid", "Khemisset", "Beni Mellal",
                   "Nador", "Tangier", "Meknes", "Settat", "Agadir", "Temara", "Tétouan", "Ben Guerir", "Ain Taoujdat",
                   "Casablanca", "Errachidia", "Ait Slimane", "Guercif", "Oujda", "Ain Harrouda", "Asni", "Sefrou",
                   "Marrakesh", "Rabat", "Khouribga", "Oulad Teima", "Oued Zem"], "HK": ["Central", "Tsuen Wan"],
            "VI": ["Frederickstadt"],
            "CA": ["Montreal", "Burnaby", "Nanaimo", "Hamilton", "Langdon", "Stoney Creek", "Brantford", "Scarborough",
                   "Windsor", "Canmore", "Vaughan", "Richmond Hill", "Victoria", "Gatineau", "St. George", "Dorval",
                   "Vancouver", "Calgary", "Whitby", "Medicine Hat", "Fort St. John", "Trenton", "Coquitlam",
                   "Stittsville", "Halifax", "Niagara Falls", "Strathroy", "Cold Lake", "Sherbrooke", "Duncan",
                   "Toronto", "Oshawa", "Saint-Constant", "Saint-Jerome", "Barrie", "Markham", "North York",
                   "Amhertsburg", "Etobicoke", "Greater Sudbury", "Langley", "Ottawa", "Beauharnois", "Mississauga",
                   "Burlington", "Marieville", "Joliette", "Brampton", "Edmonton", "Surrey", "North Vancouver",
                   "Laval"],
            "NL": ["Zutphen", "Hengelo", "Terneuzen", "Ede", "Doetinchem", "Dordrecht", "Lekkerkerk", "Zwolle",
                   "Vlaardingen", "Delfzijl", "Papendrecht", "Capelle aan den IJssel", "Ulft", "Naaldwijk", "Delft",
                   "Drempt", "Assen", "Sleeuwijk", "Leiden", "Schiedam", "Budel", "Almelo", "Winsum", "Amstelveen",
                   "Bovenkarspel", "Leusden", "Son en Breugel", "Leeuwarden", "Hardinxveld-Giessendam", "Kerkrade",
                   "The Hague", "Sliedrecht", "Hellevoetsluis", "Voorhout", "Zoetermeer", "Oegstgeest", "Lelystad",
                   "Zaandam", "Schelluinen", "Soest", "Meppel", "Arnhem", "Helmond", "Sittard", "Dronten", "Utrecht",
                   "Borculo", "Hoofddorp", "Groningen", "Duiven", "Oss", "Veldhoven", "Barendrecht", "Rotterdam",
                   "Kapelle", "Amsterdam", "Heemskerk", "Stadskanaal", "Bergen op Zoom", "Almere Stad", "Enschede",
                   "Oisterwijk", "Maastricht", "Maassluis", "Benschop", "Harlingen"], "CY": ["Nicosia", "Limassol"],
            "SK": ["Košice", "Humenné", "Nitra"],
            "CH": ["Lausanne", "Zurich", "Liebefeld", "Zweidlen-Dorf", "Gumligen", "Hochwald", "Lucerne", "Geneva",
                   "Kriens", "Buchs"],
            "CN": ["Huizhou", "Baoding", "Weifang", "Nantong", "Chengdu", "Dalian", "Hangzhou", "Jining", "Nanning",
                   "Beijing", "Dongguan", "Yangzhou", "Wuxi", "Changchun", "Chifeng", "Wuhan", "Guangzhou", "Shanghai",
                   "Nanjing", "Zhenjiang", "Shenzhen", "Dongying", "Changzhou"],
            "KZ": ["Aktobe", "Almaty", "Aktau", "Astana", "Pavlodar", "Kokshetau", "Atyrau"], "CM": ["Yaoundé"],
            "AZ": ["Baku", "Nakhchivan", "Sumqayit"], "TC": ["Providenciales"],
            "HU": ["Oroshaza", "Nagykata", "Baja", "Sarvar", "Gyal", "Budapest", "Urkut", "Nyiregyhaza", "Mako",
                   "Mohács", "Lucfalva"],
            "NP": ["Kathmandu", "Janakpur Dham", "Birtamod", "Taulihawa", "Pokhara", "Biratnagar", "Damak", "Jhapa"],
            "TH": ["Pattaya", "Nakhon Ratchasima", "Nonthaburi", "Lampang", "Surin", "Mueang Samut Prakan",
                   "Chiang Mai", "Nakhon Pathom", "Sakon Nakhon", "Bangkok", "Chanthaburi", "Chon Buri", "Bang Phli",
                   "Si Sa Ket", "Trang", "Chachoengsao", "Pak Kret", "Ko Samui", "Changwat Sara Buri"],
            "RO": ["Ineu", "Sibiu", "Bucharest", "Piatra Neamţ", "Mangalia", "Lugoj", "Galati", "Piteşti", "Ploieşti",
                   "Cernavodă", "Brad", "Bistriţa", "Urziceni", "Constanța", "Alba Iulia", "Vaslui", "Iasi", "Ilfov",
                   "Cluj-Napoca", "Pascani", "Timișoara", "Voluntari", "Mediaş", "Odorheiu Secuiesc", "Baia Mare",
                   "Slobozia", "Otopeni", "Caracal", "Bacau"],
            "BG": ["Sofia", "Varna", "Slivnitsa", "Sandanski", "Belitsa", "Sveshtari", "Dupnitsa", "Kozloduy", "Rousse",
                   "Sevlievo", "Dryanovo", "Plovdiv", "Petrich", "Ravda", "Sredets", "Blagoevgrad", "Haskovo", "Burgas",
                   "Peshtera", "Lom", "Dobrich", "Byala Slatina", "Sliven", "Ribnik"],
            "RS": ["Čačak", "Starcevo", "Rusko Selo", "Stara Pazova", "Odzaci", "Niš", "Kragujevac", "Belgrade",
                   "Senta", "Subotica", "Lazarevac", "Zrenjanin", "Novi Sad", "Smederevo", "Prokuplje", "Sombor",
                   "Basaid", "Jagodina", "Ivanjica", "Novi Pazar"],
            "EC": ["Quito", "Gualaquiza", "Rosa Zarate", "Cotacachi", "Portoviejo", "Cuenca", "Milagro",
                   "Santo Domingo de los Colorados", "Babahoyo", "Zamora", "Guayaquil", "La Concordia Numero Uno",
                   "Azogues", "Ambato"], "BN": ["Bandar Seri Begawan"], "SO": ["Merca"], "YT": ["Mtsangadoua"],
            "US": ["Fayetteville", "Oneida", "Washington", "Concord", "Bay Shore", "San Gabriel", "Louisville", "Alma",
                   "Lincoln Park", "El Paso", "Elk Grove", "Schenectady", "Beacon", "Tappahannock", "Oceanside",
                   "Philadelphia", "Cornwall-on-Hudson", "Collegeville", "Middleton", "Houston", "Odessa", "Charleston",
                   "New Smyrna Beach", "Sycamore", "Perry", "Lewisville", "Tempe", "Stockton", "Staten Island",
                   "Las Vegas", "Clarksville", "San Diego", "Porter Ranch", "Toledo", "New Philadelphia", "Manteca",
                   "Salt Lake City", "Newport Beach", "Bear", "Pittsburgh", "Harrisonburg", "Wise", "Lawrenceville",
                   "Greenville", "Tyler", "Elk Grove Village", "Lynwood", "Rancho Cucamonga", "Mission", "Honolulu",
                   "Des Plaines", "Billings", "Denver", "New York", "Eupora", "Wallingford", "Troy", "Franklin Park",
                   "Frederick", "Richardson", "Ventura", "Cleveland", "York", "Yulee", "Reno", "Baytown", "Whittier",
                   "Indianapolis", "Wichita", "Hollywood", "Lorain", "West Des Moines", "Seattle", "Arlington",
                   "Glen Burnie", "Montgomery", "Summerland Key", "Paterson", "Tulsa", "St Louis", "Council Bluffs",
                   "Cedar Knolls", "Wayne", "Encino", "Petaluma", "Henderson", "Brooklyn Park", "Rockford",
                   "Orange Park", "Santa Rosa", "Auburn", "Orlando", "Bristol", "Hawthorne", "Westland",
                   "Fort Lauderdale", "Kenosha", "Oxnard", "Fort Worth", "Lake Placid", "Justin", "Somerset", "Austin",
                   "Scappoose", "Kissimmee", "Redmond", "Midland", "Upland", "Westminster", "Fort Lee", "Iola",
                   "Meriden", "Bradenton", "Sarasota", "Rochester", "Burlingame", "Dandridge", "Pocatello", "Baker",
                   "Spring Valley", "Marion", "Cheyenne", "Clifton", "Hamilton", "Acmetonia", "West Palm Beach",
                   "Hillsboro", "Lenexa", "Steubenville", "Allentown", "Stone Mountain", "Brandon", "San Francisco",
                   "Barnegat", "Lee's Summit", "Montross", "Irvine", "Benton Harbor", "Palmdale", "Wilmington",
                   "Livermore", "Freeport", "Frisco", "Monroe", "Avenel", "Coeur d'Alene", "Mantua", "Phoenix",
                   "Fremont", "Burlington", "Westerly", "Potsdam", "Costa Mesa", "Rex", "Ashburn", "Los Angeles",
                   "Dobbs Ferry", "Lauderhill", "Tallahassee", "Glendale", "Malden", "Benton", "Milwaukee", "Spring",
                   "Durham", "Carbondale", "Harriman", "Huntington Beach", "O'Fallon", "Miami", "Latrobe", "Boydton",
                   "Victorville", "Springfield", "Shepherdsville", "North Hollywood", "La Mirada", "Conyers",
                   "Valparaiso", "San Bruno", "Eustis", "Jersey City", "Sacramento", "Memphis", "Keswick", "Raeford",
                   "Newport", "Santa Ana", "Fredericksburg", "Apple Valley", "Saint Joseph", "Columbia", "Fresno",
                   "Renton", "Inglewood", "Crestline", "Lindenhurst", "Riverside", "Cranston", "Worthington", "Gilbert",
                   "Smithtown", "Six Lakes", "Mountain View", "Omaha", "Jensen Beach", "Greenbrier", "Canyon Lake",
                   "North Kansas City", "Okeechobee", "Kansas City", "Centerville", "Kent", "Piscataway", "Portland",
                   "Canyon Country", "Katy", "Tampa", "Detroit", "Asheville", "Bowling Green", "Dulles", "Ruthven",
                   "Saint Clair", "Brooklyn", "Greeley", "St. George", "Edison", "Hixson", "Phoenixville", "Sterling",
                   "Spokane", "Round Rock", "Panama City", "DeKalb", "Lebanon", "Glenwood Springs", "La Habra",
                   "Cincinnati", "Doylestown", "Nashville", "Irving", "Ocala", "Mobile", "Madisonville", "Pittsfield",
                   "Redding", "Coral Springs", "Columbus", "Charlotte", "Hesperia", "Dumfries", "Thousand Oaks",
                   "Atlantic City", "Morehead", "Hacienda Heights", "New Castle", "Hamtramck", "Union City", "Garwood",
                   "Mount Pleasant", "Fairport", "Delray Beach", "Worcester", "Mountain Top", "San Jose", "Lakeland",
                   "Flushing", "Zanesville", "Clermont", "White Cottage", "Dayton", "Chicago", "Santa Clara",
                   "Beachwood", "Derby", "El Dorado Hills", "Gardnerville", "Independence", "Greenwood", "Manassas",
                   "Atlanta", "San Antonio", "Asbury Park", "Long Branch", "Southfield", "Clinton", "Novi",
                   "Harrodsburg", "Ellicott City", "Federal Way", "Rye", "Reston", "Kenilworth", "Valrico", "Secaucus",
                   "Overland Park", "Sterling Heights", "Gainesville", "Woodinville", "Anderson", "West Covina",
                   "Pflugerville", "Haslet", "North Bergen", "Mooresville", "Lakewood", "Long Beach", "Covina",
                   "Seaside Heights", "Hyattsville", "Milford", "Dallas", "Bakersfield", "Maryville", "Johnston",
                   "San Ramon", "Norwood", "Oak Harbor", "East Orange", "Hialeah", "Fernandina Beach", "Downingtown",
                   "Sedro-Woolley", "Guyton", "Los Banos", "Colorado Springs", "Minneapolis", "Kennewick", "The Bronx",
                   "The Dalles", "Kanab", "Garden Grove", "Vancouver", "Lubbock", "Chapel Hill", "Miamisburg",
                   "Northville", "Newark", "Parrish", "Scottsdale", "Tucson", "Jupiter", "Johns Island", "Edmonds",
                   "Plymouth", "Keller", "Boardman", "Lapeer", "Elmsford", "Saint Paul", "Denton", "Brookline",
                   "Rancho Palos Verdes", "Jacksonville", "Naples", "Castro Valley", "Plantation", "Quincy",
                   "North Charleston", "Little River", "Birmingham", "Fontana", "Albany", "Milton", "Keansburg"],
            "JP": ["Tajiri", "Hashido", "Shimoigusa", "Kugayama", "Moegino", "Higashiasahimachi", "Iwata", "Asahikawa",
                   "Onuma", "Takasago", "Habikino", "Yachiyo", "Ichibacho", "Chiyoda-ku", "Otemachi", "Aioicho",
                   "Honcho", "Ibaraki", "Sapporo", "Otemae", "Minoh", "Sagata", "Shimotsuruma", "Soga", "Kanuma",
                   "Gifu", "Yamamotodori", "Tenjin", "Ekimaedori", "Hoshigaoka", "Ikegami", "Maebashi", "Saiwaicho",
                   "Niizo", "Akasaka", "Toyonaka", "Oshiocho", "Akiyama", "Ōtsu", "Tsudanuma", "Katayamazu", "Yokohama",
                   "Asagayakita", "Machida", "Higashiomiya", "Kurashiki", "Nishikicho", "Utsunomiya", "Kamakura",
                   "Kokuba", "Toyoshiki", "Numazu", "Nagoya", "Gojo", "Suita", "Matsuyama", "Himeji", "Kurume",
                   "Kasumicho", "Kochi", "Sakai", "Minamiuebaru", "Kanazawa", "Fukuyama", "Minamishimmachi",
                   "Katsushika", "Toyama", "Ebetsu", "Oka", "Aobadai", "Kasuga", "Fujioka", "Yokkaichi", "Sakurai",
                   "Fukushima", "Inzai", "Uonuma", "Nishihama", "Tanashicho", "Edogawa", "Shikishimacho", "Tsukamoto",
                   "Hanakoganei", "Chuo", "Netabi", "Osaka", "Sendai", "Saganaka", "Chigasaki", "Niigata", "Hirakata",
                   "Ueki", "Otaru", "Hamamatsu", "Nakamura", "Kobe", "Shimizu", "Motomiya", "Hiroshima", "Kitakyushu",
                   "Takasaki", "Iruma", "Yutakacho", "Sanda Shi", "Sechigo", "Minatomirai", "Ikebukuro-honcho",
                   "Yokosuka", "Matsudo", "Shiroi", "Shizuoka", "Hitoichimachi", "Ichikawa", "Kiyokane", "Sannomaru",
                   "Momochihama", "Chiba", "Sakaecho", "Torishima", "Ida", "Kawasaki", "Jōyō", "Izumi-honcho", "Mito",
                   "Edagawa", "Shinchiba", "Kuwae", "Nakano", "Takaokanishi", "Omizo", "Ōita", "Miyazaki", "Joetsu",
                   "Sugaya", "Nagano", "Kumamoto", "Marugame", "Nishiogikita", "Meieki", "Chuodai", "Minamiedo",
                   "Adachi", "Yamagata", "Okinawa", "Handa", "Yao", "Tokyo", "Higashinakajima", "Obihiro",
                   "Shakujiimachi", "Hakatacho", "Kamimizo", "Suge-notoro", "Kofu", "Hikone", "Toyota", "Shinjo",
                   "Hamanocho", "Nagasaki", "Mori", "Ogawa", "Iikura", "Hirono", "Aisai", "Okazaki", "Imanosho",
                   "Okayama", "Kawagoe", "Koshigaya", "Natorigaoka", "Umeda", "Kashiwa", "Takamatsu", "Hakusancho-sada",
                   "Minamimorimachi", "Higashine", "Ichinomiya", "Fukuoka", "Kyoto", "Neyagawa", "Tahara", "Heiwajima",
                   "Uruma", "Karasawa", "Hiyoshi", "Hachiōji", "Takatsuki", "Meinohama", "Nakakura"],
            "AF": ["Kabul", "Jalalabad"], "LA": ["Vientiane", "Thakhek"], "VC": ["Kingstown"], "GH": ["Accra"],
            "GY": ["Georgetown"],
            "AR": ["Pilar", "Alta Gracia", "Santo Tome", "Venado Tuerto", "Ramallo", "Resistencia",
                   "Adolfo Gonzales Chaves", "San Miguel de Tucumán", "Elisa", "Gualeguaychú", "San Miguel",
                   "San Rafael", "Tres de Febrero", "Villa General Ramírez", "Córdoba", "Bovril", "San Fernando",
                   "San Vicente", "San Pedro de Jujuy", "Saladillo", "City Bell", "Balcarce", "Pinamar",
                   "Vicente Lopez", "Guernica", "Las Brenas", "Rio Grande", "Cutral-Co", "Tres Arroyos", "Chilecito",
                   "Mar del Plata", "La Plata", "Leones", "Tortuguitas", "Puerto Eldorado", "Perico",
                   "Santa Clara del Mar", "Ayacucho", "Ciudadela", "Palpala", "Wilde", "Libertador General San Martin",
                   "Campo Largo", "Rufino", "Zapala", "Leandro N. Alem", "Dolores", "Del Viso", "Moreno",
                   "San Salvador", "Orán", "La Calera", "Empalme San Vicente", "San Justo", "Villa Mercedes",
                   "Chivilcoy", "Clorinda", "Neuquén", "Zárate", "Santa Fe", "Pampa del Infierno", "Rio Primero",
                   "Trelew", "Villa Carlos Paz", "Villa Ballester", "Rosario del Tala", "Concepción del Uruguay",
                   "Longchamps", "Crespo", "Ituzaingo", "Presidencia de la Plaza", "Veinticinco de Mayo", "Berazategui",
                   "Gaiman", "Chimbas", "Federal", "Puerto Madryn", "Colon", "Necochea", "Fontana", "Tandil", "Glew",
                   "Libertad", "Pehuajó", "Villa Adelina", "Rosario", "Ingeniero Maschwitz", "Paraná", "Villa Alsina",
                   "Mercedes", "Santa Rosa", "Belen de Escobar", "Mar del Tuyu", "Beccar", "Merlo", "Oro Verde",
                   "Pergamino", "Adrogue", "Isidro Casanova", "Gobernador Crespo", "Posadas", "El Talar", "Albardon",
                   "Salsipuedes", "Barranqueras", "Cruz del Eje", "Río Gallegos", "San Juan", "San Martin", "Luján",
                   "Guatimozin", "Bahía Blanca", "Concordia", "Esther", "San Pedro", "Bella Vista", "La Rioja",
                   "Rio Segundo", "San Luis", "Lanus", "Campana", "Jose C. Paz", "Florencio Varela",
                   "San Francisco Solano", "Pico Truncado", "Junín", "28 de Noviembre", "Trenque Lauquen", "Berisso",
                   "Salta", "San Salvador de Jujuy", "Obera", "Ushuaia", "General Pinedo", "Castelar", "Curuzu Cuatia",
                   "Mendoza", "La Banda", "San Isidro", "Avellaneda", "Pilciao", "Caviahue", "Burzaco", "Laprida",
                   "Presidencia Roque Sáenz Peña", "Quilmes", "Monte Grande", "Catamarca", "Cinco Saltos", "Florida",
                   "Buenos Aires", "Río Cuarto", "Carmen de Areco", "Tunuyan", "Corrientes", "Santiago del Estero",
                   "Tigre", "Formosa", "General Roca", "Nueve de Julio", "Yerba Buena", "Hurlingham",
                   "San Francisco del Monte de Oro", "Concepcion", "Ranchos", "Olavarría", "Aguilares", "Maipu",
                   "Rodeo del Medio", "Boulogne", "Nogoya", "La Paz", "Arrecifes", "Castelli", "Montecarlo",
                   "Gonzalez Catan", "Llavallol", "Moron", "General San Martin", "Santa Teresita", "Lomas del Mirador",
                   "Caseros", "Lomas de Zamora", "La Leonesa", "Villa María", "Laferrere", "Ciudad Evita",
                   "Jesus Maria", "El Colorado", "San Jose de la Esquina", "Puerto Vilelas", "Luis Guillon", "Ensenada",
                   "Villa Madero", "Munro"], "GA": ["Libreville"], "NA": ["Walvis Bay", "Windhoek", "Swakopmund"],
            "KH": ["Siem Reap", "Phnom Penh", "Sihanoukville", "Pursat", "Bavet", "Battambang"],
            "MX": ["Venustiano Carranza", "Querétaro City", "Toluca", "Solidaridad", "Puerto Vallarta", "Parral",
                   "Ciudad Obregón", "Nogales", "Culiacán", "San Vicente", "Huauchinango", "Cabo San Lucas",
                   "Huixquilucan de Degollado", "Mexico City", "Guadalupe Trujillo", "Puente de Ixtla",
                   "San Luis Potosí City", "Zapotlanejo", "Juarez", "Tula de Allende", "Irapuato", "Atitalaquia",
                   "Ciudad Nezahualcoyotl", "Iztapalapa", "Oaxaca City", "Puebla City", "Chilpancingo", "Zapopan",
                   "Altamira", "Ensenada", "Zamora", "Naucalpan", "Lázaro Cárdenas", "Gustavo Adolfo Madero",
                   "Tlalnepantla", "Monclova", "Ciudad Juárez", "Campeche", "Cuernavaca", "Tampico", "Coyoacán", "León",
                   "Tecoman", "Torreón", "Monterrey", "Poza Rica de Hidalgo", "Tlalpan", "Macuspana", "Pachuca",
                   "Tlapa de Comonfort", "Chalco", "Puerto Peñasco", "Heroica Matamoros", "Mérida", "Chihuahua City",
                   "Centro", "Tijuana", "Ecatepec", "Xochimilco", "Coatzacoalcos", "Mazatlán", "Guaymas", "Minatitlán",
                   "Reynosa", "Jalpa de Mendez", "Hermosillo", "Guadalajara", "Mexicali", "Guadalupe"],
            "BD": ["Shailkupa", "Habiganj", "Netrakona", "Noagaon", "Mirpur", "Nilphamari", "Chuadanga", "Gazipur",
                   "Mymensingh", "Ulipur", "Feni", "Saidpur", "Ullapara", "Chittagong", "Barguna", "Rajshahi",
                   "Kishorganj", "Dhaka", "Comilla", "Bogra", "Barishal", "Raipur", "Narsingdi", "Pabna", "Noakhali",
                   "Meherpur", "Narayanganj", "Sylhet", "Jessore", "Tongi", "Manikganj", "Cox's Bazar", "Sirajganj",
                   "Sunamganj", "Gaibandha", "Bholuka"],
            "PK": ["Faisalabad", "Gujrat", "Jhelum", "Bahawalpur", "Little Attock", "Multan", "Hafizabad", "Lakki",
                   "Mandi Burewala", "Islamabad", "Karachi", "Quetta", "Rawalpindi", "Hyderabad", "Mianwali", "Sialkot",
                   "Sargodha", "Rahim Yar Khan", "Kasur", "Shahkot", "Shabqadar", "Lahore", "Gujranwala", "Pakpattan",
                   "Goth Hāla", "Rawlakot", "Mardan", "Chak Forty-two SP", "Manga Mandi", "Peshawar"],
            "GE": ["Oni", "Zugdidi", "Kutaisi", "Akhalk'alak'i", "Tbilisi", "Batumi"], "KY": ["George Town"],
            "GL": ["Aasiaat"], "MM": ["Tachilek", "Yangon", "Mandalay"], "VU": ["Norsup"],
            "FI": ["Salo", "Helsinki", "Lappeenranta"],
            "PH": ["Caloocan City", "Caba", "Malabon", "Santa Rita", "Bulacan", "Siaton", "Cainta", "Iloilo City",
                   "Davao City", "San Pablo City", "Marilao", "Angeles City", "Carmen", "Malaybalay", "Tarlac City",
                   "Panabo", "Lingayen", "Lapu-Lapu City", "Bacoor", "Calamba", "Alcala", "Quezon City",
                   "Antipolo City", "Taguig", "Masbate", "Ozamiz", "Tagudin", "Kasilawan", "Pasay", "Talavera",
                   "Carmona", "Pasig-bo", "Magugpo Poblacion", "Tuguegarao City", "Canaman", "Cadiz", "Marikina City",
                   "Cotabato City", "Saravia", "Tanjay", "Cebu City", "Lahug", "Cabanatuan City", "Malolos", "Goa",
                   "Norzagaray", "Malate", "Ramon Magsaysay", "Makati City", "La Trinidad", "San Pedro",
                   "Mandaluyong City", "Roxas City", "Laoag", "Santo Tomas", "Tabogon", "Bacolod City", "Butuan",
                   "Mandaue City", "Pototan", "Maddela", "Iligan", "General Santos", "Santa Maria", "Las Pinas", "Naga",
                   "Sorsogon", "Bislig", "Calauag", "Cabuyao", "Lipa City", "Zamboanga City", "Paranaque City",
                   "Manila", "Murcia", "San Jose", "Santa Rosa", "Rodriguez", "Umingan", "Isulan", "Pagsanjan",
                   "Cavite City", "Lagindingan", "Legazpi", "Nasugbu", "San Jose del Monte", "Urdaneta", "Batangas",
                   "Los Banos", "Calauan", "Cagayan de Oro", "Lucena City", "Binangonan", "Pasig", "San Juan",
                   "Koronadal", "Agoo", "Tabaco", "Calbayog City", "San Miguel", "Tanauan", "Kawit", "San Marcelino",
                   "Solano", "Baguio City", "Puerto Princesa City", "Tanza", "Balingasag", "Dasmarinas", "Barobo",
                   "Green Park", "Dagupan", "Pagadian", "San Carlos City", "Tagbilaran", "General Trias", "Imus",
                   "Tandag", "San Carlos", "Concepcion Dos", "Malanday", "Kidapawan", "Santiago", "Valenzuela",
                   "Bocaue", "San Fernando City", "Caruhatan", "Mabalacat"], "ER": ["Asmara"],
            "MP": ["Saipan"],
            "RU": ["Vyborg", "Nakhodka", "Izhevsk", "Yekaterinburg", "Shchelkovo", "Cheboksary", "Stupino",
                   "Kostomuksha", "Tver", "St Petersburg", "Sayanogorsk", "Petrozavodsk", "Bratsk", "Tomsk", "Magadan",
                   "Novokuznetsk", "Vladivostok", "Tikhvin", "Blagoveshchensk", "Kopeysk", "Kirov", "Yaroslavl",
                   "Rostov-on-Don", "Tuapse", "Minusinsk", "Naro-Fominsk", "Belovo", "Dolgoprudnyy", "Kaliningrad",
                   "Petropavlovsk-Kamchatsky", "Klimovsk", "Ust'-Kut", "Neftekamsk", "Kirzhach", "Pechora",
                   "Cherepovets", "Yablonitsy", "Voronezh", "Komsomolsk-on-Amur", "Penza", "Svetogorsk", "Berezniki",
                   "Zhukovskiy", "Ufa", "Orenburg", "Miass", "Smolensk", "Barnaul", "Volgograd", "Morshansk", "Abakan",
                   "Murmansk", "Bologoye-4", "Surgut", "Derbent", "Mytishchi", "Armavir", "Taganrog", "Seversk",
                   "Vyksa", "Yakutsk", "Ivanovo", "Donetsk", "Apatity", "Otradnoye", "Novorossiysk", "Ulyanovsk",
                   "Syktyvkar", "Sarov", "Krasnoyarsk", "Chelyabinsk", "Makhachkala", "Ussuriysk", "Cheremkhovo",
                   "Okha", "Saransk", "Leninogorsk", "Tolyatti", "Sochi", "Tambov", "Zagoryanskiy", "Chaykovskiy",
                   "Kanevskaya", "Mezhdurechensk", "Ust'-Ilimsk", "Omsk", "Astrakhan", "Naberezhnyye Chelny",
                   "Korolyov", "Nizhniy Novgorod", "Kostroma", "Engel's", "Chita", "Nevel", "Marfino", "Bryansk",
                   "Nal'chik", "Balashikha", "Vitimskiy", "Klin", "Kudymkar", "Kirovsk", "Vladikavkaz", "Belaya Glina",
                   "Nizhnekamsk", "Irkutsk", "Ulan-Ude", "Tula", "Korsakov", "Frolovo", "Ramenskoye", "Korkino",
                   "Novocherkassk", "Belgorod", "Monchegorsk", "Kolomna", "Kemerovo", "Poronaysk", "Krasnopol'ye",
                   "Taysara", "Kursk", "Salekhard", "Krasnodar", "Kazan'", "Arkhangelsk", "Kraskovo", "Biysk",
                   "Arsen'yev", "Dalnegorsk", "Pervouralsk", "Vsevolozhsk", "Murino", "Kolpino", "Ukhta",
                   "Zheleznogorsk", "Khabarovsk", "Angarsk", "Reutov", "Kholmsk", "Saratov", "Ishnya", "Tosno",
                   "Lipetsk", "Vologda", "Kol'chugino", "Veliky Novgorod", "Chekhov", "Oryol", "Olya", "Moscow",
                   "Tyumen", "Yuzhno-Sakhalinsk", "Novosibirsk", "Sterlitamak", "Kaluga", "Nogliki", "Yoshkar-Ola",
                   "Sergiyev Posad", "Kurgan", "Samara", "Iksha", "Koryazhma", "Nazarovo", "Obninsk", "Uzlovaya",
                   "Stavropol", "Perm", "Vladimir", "Karpinsk"],
            "CU": ["Santa Clara", "Camagüey", "San German", "La Playa", "Havana", "Bayamo"],
            "TN": ["Rades", "El Fahs", "Kelibia", "Beni Khalled", "Manouba", "Sukrah", "Mateur", "El Kef", "Gafsa",
                   "Ferryville", "Sahline", "Siliana", "Hammam Sousse", "Tajerouine", "Hammamet", "Bizerte", "Akouda",
                   "Borj Cedria", "La Marsa", "Houmt Souk", "Tebourba", "Sfax", "Medjez el Bab", "Tozeur", "Zahrouni",
                   "Sidi Bouzid", "Aryanah", "Ben Arous", "Teboulba", "Nabeul", "Zaghouan", "Megrine", "Sousse",
                   "Monastir", "Menzel Jemil", "Cité El Khadhra", "Kairouan", "Soliman", "Ksar Hellal", "Chebba",
                   "Korba", "Tunis", "Mahdia"], "LT": ["Vilnius", "Kaunas", "Klaipėda"],
            "BE": ["Zoersel", "Nieuwpoort", "Lanaken", "Overmere", "Ghent", "Mouscron", "Zuienkerke", "Couvin",
                   "Torhout", "Brussels", "Antwerp", "Zingem", "Aywaille", "Roeselare", "Roosdaal", "Messelbroek",
                   "Snaaskerke", "Namur", "Edegem", "Gavere", "Charleroi", "Battice", "Quaregnon", "Marche-en-Famenne",
                   "Riemst", "Oudenaarde", "Dilbeek"], "EE": ["Tallinn", "Jõhvi"], "MW": ["Lilongwe"],
            "LU": ["Luxembourg"],
            "DZ": ["Seddouk", "Naciria", "Bou Haroun", "Bordj Zemoura", "Telerghma", "Hassi Messaoud", "Ain Fakroun",
                   "M'Chedallah", "Maghnia", "Sougueur", "Ras el Oued", "Tissemsilt", "Béjaïa", "Collo", "Guelma",
                   "Larbaâ", "Oued el Alleug", "Heliopolis", "Ouargla", "Blida", "El Hammam", "El Aouinet", "Birtouta",
                   "Arris", "Hassi Bahbah", "Chebli", "Bir el Djir", "Draria", "Bougaa", "Mecheria", "Tidjelabine",
                   "Bir el Ater", "Azib Aboudaou", "Bou Saada", "Algiers", "Lakhdaria", "Baraki", "Ghardaïa", "Rouiba",
                   "Ain Taya", "Sétif", "Theniet el Had", "Kouba", "Zgoum", "Souk Ahras", "Mascara", "Ain Beida",
                   "Kolea", "Lardjem", "Taghit", "M'Sila", "Mostaganem", "Boumerdes", "Kouinine", "Souma", "Ghazaouet",
                   "Aflou", "Hennaya", "'Ain el Hammam", "El Eulma", "Ain Oulmene", "Constantine", "Sidi Aissa",
                   "Tébessa", "El Hadjira", "Barika", "Sidi Aich", "Berriane", "El Bayadh", "Ain Temouchent", "Jijelli",
                   "Djelfa", "Tlemcen", "Sebdou", "Boudjima", "Tolga", "El Tarf", "El Affroun", "Tiaret", "Skikda",
                   "Relizane", "Beni Amrane", "Tipasa", "Hassi Maameche", "Sidi Aoun", "Rahouia", "Didouche Mourad",
                   "Arzew", "Bordj Bou Arreridj", "Boghni", "L'Agha", "El Achour", "Feraoun", "Adrar", "Sedrata",
                   "Batna City", "Biskra", "Sidi Akkacha", "El Abadia", "Ighram", "Sidi Okba", "Bouïra", "Ain Nouissy",
                   "Laghouat", "Meskiana", "Hadjout", "Cherchell", "Amalou", "Zarzaitine", "Oran", "Abadla",
                   "ash-Shalif", "Zeralda", "Mila", "Ramdane Djamal", "El Omaria", "Taher", "Mazouna", "'Ain el Melh",
                   "Sidi Bel Abbes", "El Madania", "El Milia", "Bou Arfa", "El Oued", "Amizour", "Béchar", "Annaba",
                   "Draa Ben Khedda", "Khenchela", "Tizi Ouzou", "Saida", "Djendel", "Bab Ezzouar", "Reghaia", "Sig",
                   "Debila", "Messaad", "Tamanghasset", "Bordj el Bahri", "Medea", "Dar el Beida", "Akbou", "Nedroma",
                   "Oum el Bouaghi", "Rouina", "Boufarik", "Hammam Dalaa", "Ourlal", "Arbatache", "Berrahal",
                   "Ain Defla", "Reguiba", "Ain Touta"],
            "VN": ["Cao Lanh", "Kon Tum", "Bac Ninh", "Tam Binh", "Hanoi", "Da Nang", "Nam Định", "Tan Tuc", "Tra Vinh",
                   "Bac Giang", "Tan Phu", "Bến Tre", "Cao Bang", "Can Tho", "Thai Nguyen", "Haiphong", "Hung Yen",
                   "An Giang", "Ca Mau", "Ha Giang", "Binh Duong", "Ho Chi Minh City", "Hai Duong", "Lao Cai", "Vinh",
                   "Soc Trang", "Bien Hoa", "Viet Tri", "Tinh Binh Duong", "Sơn La", "Thai Binh", "Ninh Binh",
                   "Tay Ninh", "Lai Chau", "My Tho", "Vĩnh Long", "Vinh Yen", "Pleiku", "Vũng Tàu", "Rach Gia",
                   "Nha Trang", "Thuan An", "Tan Tien", "Thanh Hóa", "Binh Tan", "Thanh Son"],
            "LV": ["Riga", "Liepāja"], "MD": ["Chisinau", "Cahul", "Soltanesti"],
            "MU": ["Beau Bassin-Rose Hill", "Port Louis"], "SB": ["Honiara"],
            "SV": ["Zacatecoluca", "San Salvador", "Santo Tomas", "La Libertad", "Sonsonate", "Ahuachapan", "Lourdes",
                   "San Miguel", "Soyapango", "Quezaltepeque", "Santa Ana", "La Union", "San Miguel Ingenio",
                   "Usulutan", "San Martin", "Nahuizalco", "Santa Tecla"],
            "HR": ["Koprivnica", "Zagreb", "Osijek", "Rijeka", "Donja Voca", "Split"],
            "IL": ["Rishon LeTsiyyon", "Jerusalem", "Tel Aviv", "Haifa", "Holon", "Ashquelon", "Qiryat Ata"],
            "NC": ["Noumea"], "KW": ["Kuwait City"], "FM": ["State of Pohnpei"],
            "MY": ["Cyberjaya", "Shah Alam", "George Town", "Kuala Lumpur", "Petaling Jaya", "Kota Kinabalu",
                   "Puchong Batu Dua Belas", "Batu Pahat", "Kuala Terengganu", "Johor Bahru", "Ipoh"],
            "GF": ["Cayenne"], "PY": ["Caacupe", "Luque", "Asunción", "Estancia Nueva Esperanza"],
            "MG": ["Mahajanga", "Toamasina", "Antananarivo"], "KE": ["Nairobi"], "LC": ["Castries"],
            "PA": ["Panama City", "David"], "BW": ["Gaborone", "Francistown"],
            "CL": ["Santiago", "Antofagasta", "Concepción", "Futrono", "La Union", "Castro", "Iquique", "Talca",
                   "Osorno", "Quillota"], "SC": ["Victoria"], "KG": ["Bishkek"], "PF": ["Papeete"],
            "ES": ["Las Torres de Cotillas", "Puerto de la Cruz", "A Pobra do Caraminal", "Tomelloso", "Igualada",
                   "Málaga", "Elche", "Armilla", "Ripoll", "Murcia", "Madrid", "Albacete", "Boadilla del Monte",
                   "Barcelona", "Castelló de la Plana", "Ferrol", "Santa Coloma de Gramenet", "Casariche", "Torrent",
                   "Tarragona", "Jerez de la Frontera", "Espartinas", "Valencia", "Vigo"],
            "UA": ["Cherkasy", "Pobuzke", "Odesa", "Uman", "Sevastopol", "Yavoriv", "Kremenchug", "Mala Vyska",
                   "Teplodar", "Donetsk", "Mohyliv-Podilskyy", "Okhtyrka", "Kherson", "Selidovo", "Mykolayiv", "Kalush",
                   "Lviv", "Simferopol", "Horishni Plavni", "Irpin", "Hadyach", "Kyiv", "Chernihiv", "Horodok",
                   "Kamianske", "Chornomorsk", "Perechyn", "Nova Vodolaha", "Korsun-Shevchenkivskyy", "Kharkiv",
                   "Arbuzynka", "Khmelnytskyi", "Kropyvnytskyi", "Chernivtsi", "Kakhovka", "Dnipro", "Zaporizhzhya",
                   "Bila Tserkva", "Crimea", "Sambir", "Terebovlia", "Kamianets-Podilskyi", "Vinnytsia", "Polonne"],
            "GN": ["Conakry"], "GM": ["Serrekunda"],
            "IT": ["Parabiago", "Ardenno", "San Pietro a Maida", "Misano Adriatico", "Pozzuolo del Friuli",
                   "Rignano Flaminio", "Arezzo", "Milan", "Teramo", "Castelfranco Emilia", "Rome", "Aversa", "Naples",
                   "Teverola", "Arona", "Salerno", "Turin", "Città Sant'Angelo", "Baricella", "Campana",
                   "Pomigliano d'Arco", "Valdagno di Trento", "Montevarchi", "Siena", "Pescara", "Bari", "Florence",
                   "Assisi", "Siziano", "Macerata", "San Giuseppe Vesuviano", "Bologna", "Bitritto", "Vicenza",
                   "Perugia"],
            "PT": ["Matosinhos Municipality", "Lisbon", "Caldas da Rainha", "Oia", "Ponta Delgada", "Coimbra",
                   "Barreiro", "Covilha", "Retorta", "Vila Nova de Gaia", "Golega", "Leiria", "Vila Nova de Famalicao",
                   "Guimarães", "Oeiras", "Arcozelo", "Odivelas", "Amadora", "Evora", "Estoril", "Oliveira do Bairro"],
            "BO": ["Sucre", "Cochabamba", "Oruro", "Yacuiba", "La Paz", "Santa Cruz"], "FJ": ["Lautoka", "Suva"],
            "NZ": ["Auckland", "Tauranga", "Christchurch"],
            "NO": ["Gressvik", "Trondheim", "Oslo", "Strauman", "Tromsø", "Mandal"], "SR": ["Paramaribo"],
            "GB": ["Havant", "Barnet", "Hayes", "Waltham Abbey", "Southsea", "Islington", "Burnley", "Cardiff",
                   "Hartlepool", "Lambeth", "Walsall", "Watford", "Colchester", "Oldbury", "Glasgow", "Belfast",
                   "Wimborne Minster", "Rothwell", "South Shields", "Brent", "Motherwell", "Bristol", "Bognor Regis",
                   "Manchester", "Darlington", "Thurso", "Brierley Hill", "Kettering", "Northampton", "Epsom", "Harrow",
                   "Porth", "Edinburgh", "Blackburn", "St Helens", "Dagenham", "Southport", "Sheffield", "New Milton",
                   "Cheltenham", "Huntingdon", "Maidstone", "Dunstable", "Thornton Heath", "Portsmouth", "Birmingham",
                   "Banbury", "Margate", "London", "Bromley", "Wakefield", "Dartford", "Corby", "Hemel Hempstead",
                   "High Wycombe", "Chelmsford", "Greenford", "Wembley", "Cambridge", "Great Malvern", "Leyton",
                   "Maidenhead", "Bedford", "Aylesbury", "Liverpool", "Brighton", "Leeds", "Ormskirk", "Coventry"],
            "PL": ["Suchy Las", "Pisz", "Skarzysko-Kamienna", "Siedlisko", "Pruszków", "Wyszków", "Lublin", "Pajeczno",
                   "Wroclaw", "Ruda Śląska", "Radomsko", "Piaseczno", "Warsaw", "Lodz", "Gdansk", "Zglobice",
                   "Częstochowa", "Glogowek", "Stalowa Wola", "Krakow", "Gdynia"],
            "MK": ["Tetovo", "Gevgelija", "Skopje"],
            "BA": ["Mostar", "Brcko", "Sekovici", "Visoko", "Sarajevo", "Banja Luka", "Tuzla", "Gracanica"],
            "GP": ["Pointe-à-Pitre", "Petit-Bourg", "Les Abymes", "Morne-a-l'Eau", "Capesterre-Belle-Eau"],
            "MT": ["Sliema", "Qormi", "Zejtun", "Ghajnsielem", "Swieqi"],
            "IQ": ["Al Hillah", "Basrah", "Kirkuk", "Tikrit", "Sulaymaniyah", "Karbala", "Erbil", "Kut", "Al Anbar",
                   "Najaf", "Mosul", "Fallujah", "Ramadi", "Hayy al Muthanna", "Baghdad", "Duhok", "Baqubah", "Samarra",
                   "Ar Rumaythah", "Raniye"],
            "AU": ["Melbourne", "Bungarribee", "Canberra", "Sydney", "Perth", "Adelaide"]}

username = "ishogbon"
password = "bc0151-0a8b75-3d55b3-329f8f-a69473"

PROXY_RACK_DNS = "premium.residential.proxyrack.net:10000"


lists = {}
for country in country_list:
    # Make a request to api.proxyrack.net/countries to see a list of available countries for geo-targeting
    urlToGet = f"http://api.proxyrack.net/countries/{country}/cities";

    proxy = {"http": "http://{}:{}@{}".format(username, password, PROXY_RACK_DNS)}

    cities = requests.get(urlToGet, proxies=proxy).json()
    lists[country] = []
    for city in cities:
        lists[country].append(city)
print(lists)
